/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProxyAdmin__factory } from "./ProxyAdmin__factory";
export { ZeroHero__factory } from "./ZeroHero__factory";
